/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Trading_one_monthRouteImport } from './routes/trading_one_month'
import { Route as IndexRouteImport } from './routes/index'

const Trading_one_monthRoute = Trading_one_monthRouteImport.update({
  id: '/trading_one_month',
  path: '/trading_one_month',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trading_one_month': typeof Trading_one_monthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trading_one_month': typeof Trading_one_monthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trading_one_month': typeof Trading_one_monthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trading_one_month'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trading_one_month'
  id: '__root__' | '/' | '/trading_one_month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Trading_one_monthRoute: typeof Trading_one_monthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trading_one_month': {
      id: '/trading_one_month'
      path: '/trading_one_month'
      fullPath: '/trading_one_month'
      preLoaderRoute: typeof Trading_one_monthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Trading_one_monthRoute: Trading_one_monthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
